project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "TMCA Urban Soil Mapping Meeting Minutes"
  author: "N.A. Jelinski, N.B. Pearson"
  date: "05-September-2024"
  cover-image: "TCMA-urban-soil-mapping-badge-13.png"
  
  chapters:
    - index.qmd
    - part: "Project Wide Meetings"
      chapters:
      - minutes-15DEC2023-admin-kickoff.qmd
      - minutes-15DEC2023-technical-kickoff.qmd
      - minutes-12JAN2024-dsp.qmd
      - minutes-12JAN2024-qa-qc-nasis.qmd
    - part: "Small Group Meetings"
      chapters:
      - minutes-02FEB2024-joe-nic-nora.qmd
      - minutes-02FEB2024-nic-nora.qmd
      - minutes-20FEB2024-patty-nic-nora.qmd
      - minutes-27FEB2024-nic-nora-geospatial.qmd
      - minutes-28FEB2024-patty-nic-nora.qmd
      - minutes-06MAR2024-patty-nora.qmd
      - minutes-12MAR2024-patty-nic-nora.qmd
      - minutes-20MAR2024-patty-nic-nora.qmd
      - minutes-27MAR2024-patty-nora.qmd
      - minutes-17APR2024-patty-nora.qmd
      - minutes-24APR2024-patty-nic-nora.qmd
      - minutes-07MAY2024-nic-nora.qmd
      - minutes-08MAY2024-patty-nora.qmd
      - minutes-15MAY2024-patty-nora.qmd
      - minutes-28MAY2024-field-work-team.qmd
      - minutes-29MAY2024-patty-nora.qmd
      - minutes-17JUN2024-patty-nora.qmd
      - minutes-08JUL2024-patty-nora.qmd
      - minutes-15JUL2024-patty-nora.qmd
      - minutes-05AUG2024-patty-nora.qmd
      - minutes-12AUG2024-patty-nora.qmd
      - minutes-19AUG2024-patty-nora.qmd
      - minutes-26AUG2024-patty-nora.qmd
    # - authorship-guidelines.qmd
    # - references.qmd
  # appendices:
    # - co-authorship-template.qmd
    # - data-use-and-sharing.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


